FROM ubuntu:22.04
RUN apt-get update -y  \
&& apt-get install gawk -y \
&& apt-get install python3 -y \
&& apt-get install python3-pip -y \
&& python3 -m pip install biopython \
&& apt-get install ncbi-blast+=2.12.0+ds-3build1 -y