FROM rocker/r-ver:4.6.0
ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        build-essential wget pigz git parallel ncbi-blast+ \
        autoconf automake libtool \
        libcurl4-gnutls-dev libxml2-dev libssl-dev \
        libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev \
        libpng-dev libtiff-dev libjpeg-dev perl \
        libdw1 libuv1 libnghttp2-14 locales libgit2-dev \
    && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/shenwei356/seqkit/releases/download/v2.13.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz && \
    tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ && rm /tmp/seqkit.tar.gz
RUN git clone --branch v2.30.4 https://github.com/torognes/vsearch.git \
    && cd vsearch && ./autogen.sh && ./configure && make && make install
RUN Rscript -e 'install.packages("data.table", dependencies=TRUE , repos="https://cloud.r-project.org")' \
    && Rscript -e 'install.packages("optparse", repos="https://cloud.r-project.org")' \
    && Rscript -e 'install.packages("dplyr", repos = "https://cloud.r-project.org/" )' \
    && Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org/")' \
    && Rscript -e 'install.packages("openssl", dependencies=TRUE, repos = "https://cloud.r-project.org/")' \
    && Rscript -e 'install.packages("devtools", dependencies=TRUE, repos = "https://cloud.r-project.org/")' \
    && Rscript -e 'install.packages("seqinr", dependencies=TRUE, repos = "https://cloud.r-project.org/")'
RUN Rscript -e 'install.packages("BiocManager")'
RUN Rscript -e 'BiocManager::install(version = "3.24", ask=FALSE)'
RUN Rscript -e 'BiocManager::install("dada2")'
RUN Rscript -e 'remotes::install_github("tobiasgf/lulu")'
RUN wget https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/ORFfinder/linux-i64/ORFfinder.gz
RUN gunzip ORFfinder.gz
RUN chmod 755 ORFfinder
RUN mv ORFfinder /bin/.
#ADD src/pipecraft-core/service_scripts/submodules /bin/submodules