# Use a lightweight Python base image
FROM ubuntu:24.04

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    wget \
    libgsl-dev \
    ca-certificates \
    autoconf \
    automake \
    libtool && \
    rm -rf /var/lib/apt/lists/*

# Download and install ViennaRNA
RUN wget https://github.com/ViennaRNA/ViennaRNA/archive/refs/tags/v2.7.0.tar.gz && \
    tar -xzf v2.7.0.tar.gz && \
    cd v2.7.0 && \
    autoreconf -i && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf ViennaRNA-2.7.0 v2.7.0.tar.gz

# Test installation
RUN RNAfold --version