FROM ubuntu:22.04
RUN apt-get update -y \
&& apt-get install build-essential -y \
&& apt-get install git -y \
&& apt-get install wget -y \
&& apt-get install pigz -y \
&& wget https://github.com/shenwei356/seqkit/releases/download/v2.3.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz \
&& tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ \
&& rm /tmp/seqkit.tar.gz \
&& DEBIAN_FRONTEND=noninteractive apt-get -qq install r-base -y \
&& apt-get install ncbi-blast+ -y \
&& apt-get install autoconf -y \
&& git clone --branch v2.18.0 https://github.com/torognes/vsearch.git \
&& cd vsearch && ./autogen.sh && ./configure && make && make install \
&& apt-get install r-cran-devtools -y \
&& apt-get install libcurl4-openssl-dev -y
RUN Rscript -e 'install.packages("dplyr")'
RUN Rscript -e 'library("devtools"); devtools::install_github("benjjneb/dada2", ref="v1.20")'
RUN wget https://github.com/tobiasgf/lulu/archive/refs/heads/master.zip \ 
&& Rscript  -e 'devtools::install_local("/master.zip")' \
&& rm /master.zip
RUN Rscript -e 'install.packages("seqinr")'