FROM ubuntu:24.04
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
RUN apt-get update && \
    apt-get install wget -y


ENV CONDA_DIR=/opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH
ADD image_development/OptimOTU_v3.yml /OptimOTU_v3.yml
RUN conda env create -f /OptimOTU_v3.yml    


ENTRYPOINT ["bash", "-c", "eval \"$(conda shell.bash hook)\" && conda activate OptimOTU_v3 && exec bash"]
