FROM ubuntu:22.04
RUN apt-get update
RUN apt install default-jre  -y
RUN apt install wget -y
RUN wget -qO- get.nextflow.io | bash
RUN chmod 777 nextflow
RUN mv nextflow /usr/local/bin/
RUN wget https://github.com/shenwei356/seqkit/releases/download/v2.3.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz  \
    && tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ && rm /tmp/seqkit.tar.gz