FROM ubuntu:24.04
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
RUN apt-get update && \
    apt-get install wget -y && \
    apt-get install libuv1 -y && \
    apt-get install libdw-dev -y && \
    apt-get install -y libnghttp2-14 && \
    apt-get install parallel -y

ENV CONDA_DIR=/opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

RUN <<EOF cat > /vsearch_dada2_v3.yml
name: vsearch_dada2_v3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blast=2.16.0  
  - vsearch=2.29.4
  - seqkit=2.9.0
  - pigz=2.8
  - cutadapt=5.0
  - bioconductor-dada2=1.34.0
  - r-dplyr 1.1.4
  - r-devtools 2.4.5
EOF

RUN conda env create -f /vsearch_dada2_v3.yml

RUN eval "$(conda shell.bash hook)" && \
    conda activate vsearch_dada2_v3 && \
    Rscript -e "library(devtools); devtools::install_github('tobiasgf/lulu')"

RUN wget ftp://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/ORFfinder/linux-i64/ORFfinder.gz && \
    gunzip ORFfinder.gz && \
    chmod 755 ORFfinder && \
    mv ORFfinder /bin/.


ENTRYPOINT ["bash", "-c", "eval \"$(conda shell.bash hook)\" && conda activate vsearch_dada2_v3 && exec bash"]
