FROM ubuntu:22.04
ENV TZ=Europe/Tallinn
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \ 
&& apt-get update -y \
&& apt-get install build-essential -y \
&& apt-get install pigz -y \
&& apt-get install git -y \
&& apt-get install wget -y \
&& apt-get install r-base-dev -y \
&& apt-get install r-base -y \
&& apt-get install libcurl4-gnutls-dev  -y \
&& apt-get install libxml2-dev -y \
&& apt-get install libssl-dev -y \
&& wget https://github.com/shenwei356/seqkit/releases/download/v2.3.0/seqkit_linux_amd64.tar.gz -O /tmp/seqkit.tar.gz \
&& tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ \
&& rm /tmp/seqkit.tar.gz \
&& wget https://github.com/tobiasgf/lulu/archive/refs/heads/master.zip
ADD image_development/dada2_install.R /
RUN Rscript dada2_install.R \
&& apt-get install ncbi-blast+ -y \
&& apt-get install autoconf -y \
&& git clone --branch v2.18.0 https://github.com/torognes/vsearch.git \
&& cd vsearch && ./autogen.sh && ./configure && make && make install